Feature user store
Friend34you/wilix-blog pull request #20
Opened 2023-12-11 13:42 UTC by Friend34you

Там 2 метода почти полностью идентичны, имеет ли смысл их объединять ?

2023-12-11 14:01 UTC, ivanskopincev requested changes

2023-12-11 14:01 UTC, ivanskopincev commented on src/api/axiosInstance.ts
> +  if (localStorage.getItem("token")) {
нужно переписать условие

2023-12-11 14:01 UTC, ivanskopincev commented on src/api/axiosInstance.ts
> +  return config;
точно надо?

2023-12-11 14:01 UTC, ivanskopincev commented on src/components/App.tsx
> +function testLogout() {
название огонь

2023-12-11 14:01 UTC, ivanskopincev commented on src/components/App.tsx
> +        email: "vovan23doni@gmail.com",
креды прям так оставлять сомнительное решение

2023-12-11 14:01 UTC, ivanskopincev commented on src/components/App.tsx
>      return <h1>Loading...</h1>;
хоть бы спиннер нарисовал)

2023-12-11 14:01 UTC, ivanskopincev commented on src/components/App.tsx
> +      <p>{userStore.user?.username}</p>
если нет username надо ли рендерить параграф?

2023-12-11 14:01 UTC, ivanskopincev commented on src/components/App.tsx
>        <TagsCloud tags={tagsStore.tags}/>
это еще не починилось?

2023-12-11 14:01 UTC, ivanskopincev commented on src/store/usersStore.ts
> +      this.getUser();
у тебя есть `getUser` и геттер `user` как-то масло масленое

2023-12-11 14:01 UTC, ivanskopincev commented on src/store/usersStore.ts
> +      const userResponseData = response.data.user;
можно так)
```
const { email, username, token } = response.data.user
```

2023-12-11 14:01 UTC, ivanskopincev commented on src/store/usersStore.ts
> +  loginUser = async (userData: LoginUserType) => {
тут разные роуты и эти два метода должны быть отдельно друг от друга
но если у тебя одинаковая постобработка то ее ты можешь вынести в отдельный метод

2023-12-11 15:34 UTC, Friend34you commented on src/api/axiosInstance.ts
> +  return config;
еп,надо

2023-12-11 15:46 UTC, Friend34you commented on src/components/App.tsx
>      return <h1>Loading...</h1>;
нарисовал

2023-12-11 15:47 UTC, Friend34you commented on src/components/App.tsx
>        <TagsCloud tags={tagsStore.tags}/>
добавил тудушку

2023-12-11 19:14 UTC, ivanskopincev commented on src/components/App.tsx
> +        email: import.meta.env.VITE_TEST_LOGIN,
`process.env`?

2023-12-11 19:14 UTC, ivanskopincev commented on src/components/App.tsx
> +        email: import.meta.env.VITE_TEST_LOGIN,
и почему все энвы с префиксом `VITE`?

2023-12-12 07:51 UTC, ivanskopincev approved these changes

2023-12-12 07:52 UTC, merged