Feature effector stores
Friend34you/wilix-blog pull request #50
Opened 2024-01-09 14:14 UTC by Friend34you

2024-01-10 09:03 UTC, ivanskopincev requested changes

2024-01-10 09:03 UTC, ivanskopincev commented on src/components/NewArticle.tsx
> +import articlesStore from "../store/ArticlesStoreEffector.ts";
нет смысла переименовывать в эффектор. а то каждый раз при переезде придется переименовывать. в общем не очень практика

2024-01-10 09:03 UTC, ivanskopincev commented on src/components/TagsCloud.tsx
> +import tagsStore from "../store/TagsStoreEffector";
ну тут и дальше то же самое

2024-01-10 09:03 UTC, ivanskopincev commented on src/components/article/Article.tsx
>    function handleOnFavoriteClick() {
это бы в `useCallback`

2024-01-10 09:03 UTC, ivanskopincev commented on src/components/article/Article.tsx
>    function handleOnFollowClick() {
это бы в `useCallback`

2024-01-10 09:03 UTC, ivanskopincev commented on src/components/router/AppRouter.tsx
>  //TODO: добавить NotFound component
это реализовано?

2024-01-10 09:21 UTC, Friend34you commented on src/components/router/AppRouter.tsx
>  //TODO: добавить NotFound component
нет, висит в задачах

2024-01-10 11:15 UTC, ivanskopincev requested changes

2024-01-10 11:15 UTC, ivanskopincev commented on src/components/article/Article.tsx
>      articlesStore
здесь тоже можно использовать врота

2024-01-12 10:03 UTC, ivanskopincev approved these changes

2024-01-12 10:13 UTC, merged