Feature article card
Friend34you/wilix-blog pull request #8
Opened 2023-12-04 15:12 UTC by Friend34you

Ебашь. Единственное, в app.tsx компонент подключен ток для вёрстки

2023-12-04 15:19 UTC, ivanskopincev requested changes

2023-12-04 15:19 UTC, ivanskopincev commented on src/components/ArticleCard.tsx
> +    return favorited
через обычный if будет немного читаемее

2023-12-04 15:19 UTC, ivanskopincev commented on src/components/ArticleCard.tsx
> +          <Tag key={index}>{tag}</Tag>)}
тут с форматированием беда
и если у компонента есть children лучше разносить по строкам
```
<Tag key={index}>
  {tag}
</Tag>
```

2023-12-04 15:19 UTC, ivanskopincev commented on src/components/ArticleCard.tsx
> +          <Tag key={index}>{tag}</Tag>)}
index не желательно использовать для ключа

2023-12-04 15:19 UTC, ivanskopincev commented on src/helpers/formatDate.ts
> +export const formatDate = (inputDate: string): string => {
можно заюзать либу для работы с датами)

2023-12-04 15:19 UTC, ivanskopincev commented on src/types/articleType.ts
> +  body?: string;
лучше группировать обязательные и опциональные пропсы
сначала объявляешь все обязательные, потом необязательные

2023-12-04 15:22 UTC, Friend34you commented on src/helpers/formatDate.ts
> +export const formatDate = (inputDate: string): string => {
С первого взгляда тут не особо много работы с датами, думаю, нет смысла юзать либу ради одной функции

2023-12-05 08:32 UTC, ivanskopincev requested changes

2023-12-05 08:32 UTC, ivanskopincev commented on src/components/ArticleCard.tsx
> +  const tagItems = tagList.map( tag =>
`( tag` лишний пробел

2023-12-05 08:32 UTC, ivanskopincev commented on src/components/ArticleCard.tsx
> +  const tagItems = tagList.map( tag =>
это никак не мемоизировано и будет вычисляться каждый рендер
можно обернуть в `useMemo` но лучшим решением будет вынести в отдельный компонент

2023-12-05 09:01 UTC, ivanskopincev requested changes

2023-12-05 09:01 UTC, ivanskopincev commented on src/components/TagsList.tsx
> +  const tagItems = tags.map(tag =>
почему бы сразу не в `return`?)

2023-12-05 09:01 UTC, ivanskopincev commented on src/components/TagsList.tsx
> +  const tagItems = tags.map(tag =>
и в этот компонент бы обертку тоже засунуть
вот эту
```
      <Flex
        justify={"end"}
        wrap={"wrap"}
      >
```

2023-12-05 09:18 UTC, ivanskopincev approved these changes

2023-12-05 09:18 UTC, ivanskopincev commented on src/components/TagsList.tsx
> +const TagsList:FC<TagsListProps> = ({
`TagsList:FC` пробелы украли)

2023-12-05 09:24 UTC, merged